-- =====================================================================
-- AuraStore seed data (ticket F-07): 6 categories + 24 products
-- Run in: Supabase dashboard > SQL Editor > New query > paste > Run
-- Safe to run again: products and categories are matched by slug and
-- updated, never duplicated. Re-running does NOT reset stock_qty,
-- ratings or review counts, so real orders are not undone.
-- Prices are whole naira. Image paths are relative to the site root:
--   images/products/<slug>/1.jpg, 2.jpg, 3.jpg
-- =====================================================================

-- ---------------------------------------------------------------------
-- 1. CATEGORIES
-- ---------------------------------------------------------------------
insert into public.categories (name, slug, sort_order) values
  ('Audio',              'audio',              1),
  ('Peripherals',        'peripherals',        2),
  ('Displays',           'displays',           3),
  ('Accessories',        'accessories',        4),
  ('Power and Charging', 'power-and-charging', 5),
  ('Workspace',          'workspace',          6)
on conflict (slug) do update
  set name = excluded.name, sort_order = excluded.sort_order;

-- ---------------------------------------------------------------------
-- 2. PRODUCTS
-- ---------------------------------------------------------------------
insert into public.products
  (slug, name, brand, category_id, price, old_price, stock_qty, rating_avg, rating_count,
   badge, short_description, description, highlights, specifications, box_contents,
   warranty, image_urls, is_featured)
values

-- ============================ AUDIO ============================
('sonara-studio-headphones',
 'Wireless Noise-Cancelling Studio Headphones', 'Sonara',
 (select id from public.categories where slug='audio'),
 385000, 450000, 14, 4.7, 312, 'Best seller',
 'Over-ear Bluetooth headphones with hybrid noise cancelling and 40-hour battery.',
 $d$Block out the noise of traffic, generators and open offices with the Sonara Studio. Hybrid active noise cancelling listens to your surroundings and removes up to 95 percent of low-frequency sound, so your music stays clear at lower volume. The 40mm drivers deliver deep bass and crisp vocals, while soft memory-foam ear cushions stay comfortable through long listening sessions. Fold them flat into the hard travel case when you are on the move. Connect two devices at once, take calls with the built-in beamforming microphones, and get a full day of use from a single charge. A quick 10-minute charge gives you around five hours of playback.$d$,
 array['Hybrid active noise cancelling with transparency mode',
       'Up to 40 hours of playback, 5 hours from a 10-minute charge',
       'Connects to two devices at once (Bluetooth 5.3)',
       'Memory-foam ear cushions for all-day comfort',
       'Foldable design with hard travel case',
       'Built-in microphones for clear calls'],
 '{"Type":"Over-ear, closed-back","Connectivity":"Bluetooth 5.3, 3.5mm cable","Driver Size":"40mm","Battery Life":"Up to 40 hours (ANC on)","Charging":"USB-C, 10 min gives 5 hours","Weight":"265 g","Colour":"Midnight Black","Microphone":"4-mic beamforming array"}'::jsonb,
 array['Headphones','Hard travel case','USB-C charging cable','3.5mm audio cable','Quick start guide'],
 '12 months seller warranty',
 array['images/products/sonara-studio-headphones/1.jpg','images/products/sonara-studio-headphones/2.jpg','images/products/sonara-studio-headphones/3.jpg'],
 true),

('sonara-anc-earbuds',
 'True Wireless Earbuds with ANC', 'Sonara',
 (select id from public.categories where slug='audio'),
 118000, 135000, 40, 4.5, 541, 'Popular',
 'Compact true wireless earbuds with active noise cancelling and 28-hour total battery.',
 $d$Small, light and ready for the daily commute. These Sonara earbuds combine active noise cancelling with a secure in-ear fit, so you can focus on your music, podcast or call wherever you are. Six hours of playback per charge, plus three more charges in the pocket-sized case, takes you through most of a week of commuting. Touch controls let you play, pause, skip and answer calls without reaching for your phone. With IPX4 water resistance, a sweaty workout or a light drizzle is no problem. Four sizes of ear tips are included so you can find your best fit and the best bass.$d$,
 array['Active noise cancelling and ambient sound mode',
       '6 hours per charge, 28 hours with the case',
       'IPX4 sweat and splash resistance',
       'Touch controls for music and calls',
       'Four sizes of silicone ear tips included',
       'Wireless charging case'],
 '{"Type":"True wireless, in-ear","Connectivity":"Bluetooth 5.3","Driver Size":"11mm","Battery Life":"6 hours (earbuds), 28 hours (with case)","Charging":"USB-C and wireless","Water Resistance":"IPX4","Weight":"5 g per earbud","Colour":"Graphite"}'::jsonb,
 array['Two earbuds','Charging case','USB-C cable','4 pairs of ear tips (XS, S, M, L)','User guide'],
 '12 months seller warranty',
 array['images/products/sonara-anc-earbuds/1.jpg','images/products/sonara-anc-earbuds/2.jpg','images/products/sonara-anc-earbuds/3.jpg'],
 true),

('bassline-bluetooth-speaker',
 'Portable Waterproof Bluetooth Speaker', 'Bassline',
 (select id from public.categories where slug='audio'),
 76500, null, 25, 4.4, 228, null,
 'Rugged IP67 speaker with 360-degree sound and 20 hours of playtime.',
 $d$Take the party anywhere with the Bassline Go. Its dual passive radiators push out surprisingly deep bass for a speaker this size, and the 360-degree design fills a room, a compound or a beach with even sound. The IP67 rating means it survives rain, splashes and accidental drops in the pool, and it even floats. Around 20 hours of playtime keeps you going through a long weekend. Pair two Bassline speakers together for true stereo, or link more for bigger gatherings. A built-in microphone lets you take calls hands-free, and the carry strap clips to a bag or belt loop.$d$,
 array['IP67 waterproof and dustproof, floats on water',
       'Up to 20 hours of playtime',
       '360-degree sound with deep bass',
       'Pair two speakers for stereo sound',
       'Built-in microphone for hands-free calls',
       'Durable carry strap'],
 '{"Type":"Portable Bluetooth speaker","Connectivity":"Bluetooth 5.3, AUX","Output Power":"20W","Battery Life":"Up to 20 hours","Charging":"USB-C, about 3 hours","Water Resistance":"IP67","Weight":"620 g","Colour":"Ocean Blue"}'::jsonb,
 array['Bluetooth speaker','USB-C charging cable','Carry strap','Quick start guide'],
 '12 months seller warranty',
 array['images/products/bassline-bluetooth-speaker/1.jpg','images/products/bassline-bluetooth-speaker/2.jpg','images/products/bassline-bluetooth-speaker/3.jpg'],
 false),

('voxa-usb-microphone',
 'USB Condenser Microphone with Stand', 'Voxa',
 (select id from public.categories where slug='audio'),
 92000, 105000, 18, 4.6, 167, 'Deal',
 'Plug-and-play studio condenser microphone for streaming, podcasts and calls.',
 $d$Sound like a professional without a complicated setup. The Voxa Studio USB microphone plugs straight into your laptop or desktop and works right away, with no drivers and no audio interface needed. The large-diaphragm condenser capsule captures warm, detailed vocals, and the cardioid pattern focuses on your voice while reducing keyboard clicks and room noise. A gain knob, mute button and headphone jack with zero-latency monitoring sit right on the body, so you hear exactly what your audience hears. The sturdy desktop stand and shock-absorbing design keep recordings clean. Ideal for podcasting, streaming, online classes and remote meetings.$d$,
 array['Plug and play over USB, no drivers needed',
       'Cardioid pattern reduces background noise',
       'Zero-latency headphone monitoring',
       'Gain control and one-touch mute',
       'Sturdy desktop stand included',
       'Works with Windows, macOS and most streaming apps'],
 '{"Type":"USB condenser","Polar Pattern":"Cardioid","Sample Rate":"48 kHz / 24-bit","Frequency Response":"20 Hz to 20 kHz","Connection":"USB-C","Headphone Output":"3.5mm","Cable Length":"2 m","Colour":"Matte Black"}'::jsonb,
 array['Microphone','Desktop stand','USB-C to USB-A cable','User guide'],
 '12 months seller warranty',
 array['images/products/voxa-usb-microphone/1.jpg','images/products/voxa-usb-microphone/2.jpg','images/products/voxa-usb-microphone/3.jpg'],
 false),

-- ========================= PERIPHERALS =========================
('keyforge-mechanical-keyboard',
 'Hot-Swappable Mechanical Keyboard', 'KeyForge',
 (select id from public.categories where slug='peripherals'),
 275000, null, 3, 4.8, 94, 'New',
 'Wireless 75% mechanical keyboard with hot-swappable switches and RGB lighting.',
 $d$Type on a keyboard built to feel as good as it looks. The KeyForge 75 uses a compact layout that keeps the arrow keys and function row while saving desk space. Hot-swappable sockets let you change switches in seconds without any soldering, so you can tune the feel to your taste. A gasket-mounted aluminium frame and sound-dampening foam give a soft, satisfying typing sound. Connect by Bluetooth to three devices, through the 2.4GHz receiver for low latency, or by USB-C cable. The 4,000mAh battery lasts weeks on a single charge, and per-key RGB lighting can be customised or switched off.$d$,
 array['Hot-swappable switches, no soldering needed',
       'Gasket-mounted aluminium body with sound dampening',
       'Bluetooth, 2.4GHz wireless and USB-C wired modes',
       'Per-key RGB backlight',
       '4,000mAh battery for weeks of use',
       'Works with Windows and macOS'],
 '{"Layout":"75 percent, 82 keys","Switches":"Linear, hot-swappable","Connectivity":"Bluetooth 5.1, 2.4GHz, USB-C","Battery":"4,000mAh","Backlight":"Per-key RGB","Case Material":"Aluminium","Keycaps":"PBT double-shot","Weight":"1.1 kg"}'::jsonb,
 array['Keyboard','2.4GHz USB receiver','USB-C cable','Keycap and switch puller','Spare switches (5)','Quick start guide'],
 '12 months seller warranty',
 array['images/products/keyforge-mechanical-keyboard/1.jpg','images/products/keyforge-mechanical-keyboard/2.jpg','images/products/keyforge-mechanical-keyboard/3.jpg'],
 true),

('glide-wireless-mouse',
 'Wireless Ergonomic Mouse', 'Glide',
 (select id from public.categories where slug='peripherals'),
 48500, 55000, 60, 4.5, 402, 'Popular',
 'Comfortable contoured mouse with silent clicks, 4,000 DPI and dual wireless modes.',
 $d$Long hours at the computer should not mean a sore wrist. The Glide ergonomic mouse has a sculpted shape and thumb rest that keep your hand in a natural position, reducing strain through the working day. Silent-click buttons keep shared offices and late-night sessions quiet. Switch between Bluetooth and the 2.4GHz receiver, and use the DPI button to move from precise design work to fast navigation across multiple screens. A single AA battery lasts up to 12 months, so you will almost forget about charging. Compatible with Windows, macOS, Linux and ChromeOS.$d$,
 array['Contoured shape with thumb rest for less wrist strain',
       'Silent-click buttons',
       'Bluetooth and 2.4GHz dual connection',
       'Adjustable 800 to 4,000 DPI',
       'Up to 12 months on one AA battery',
       'Works with Windows, macOS, Linux and ChromeOS'],
 '{"Type":"Wireless optical mouse","Connectivity":"Bluetooth 5.0, 2.4GHz","DPI":"800 / 1,600 / 2,400 / 4,000","Buttons":"6","Battery":"1 x AA (included)","Battery Life":"Up to 12 months","Weight":"95 g","Colour":"Charcoal Grey"}'::jsonb,
 array['Mouse','USB receiver (stored in base)','1 x AA battery','User guide'],
 '12 months seller warranty',
 array['images/products/glide-wireless-mouse/1.jpg','images/products/glide-wireless-mouse/2.jpg','images/products/glide-wireless-mouse/3.jpg'],
 true),

('clearcam-1080p-webcam',
 '1080p Webcam with Privacy Shutter', 'Clearcam',
 (select id from public.categories where slug='peripherals'),
 58000, null, 35, 4.3, 189, null,
 'Full HD webcam with autofocus, dual microphones and a physical privacy shutter.',
 $d$Look sharp on every video call, class and interview. The Clearcam delivers smooth Full HD video at 30 frames per second with automatic light correction, so you look clear even in a dim room. Autofocus keeps you sharp as you move, and the wide 90-degree lens fits you and your background in frame. Dual noise-reducing microphones pick up your voice without harsh echo. When the call ends, slide the physical privacy shutter across the lens for peace of mind. It clips onto any monitor or laptop, or sits on a tripod using the standard screw thread. No software is needed. Plug it in and it works.$d$,
 array['Full HD 1080p video at 30 fps',
       'Autofocus and automatic low-light correction',
       'Physical privacy shutter',
       'Dual noise-reducing microphones',
       'Universal clip, tripod-ready',
       'Plug and play, no drivers'],
 '{"Resolution":"1920 x 1080 at 30 fps","Field of View":"90 degrees","Focus":"Autofocus","Microphone":"Dual, noise reducing","Connection":"USB-A","Cable Length":"1.5 m","Compatibility":"Windows, macOS, ChromeOS","Mount":"Monitor clip and 1/4 inch tripod thread"}'::jsonb,
 array['Webcam with attached cable','Quick start guide'],
 '12 months seller warranty',
 array['images/products/clearcam-1080p-webcam/1.jpg','images/products/clearcam-1080p-webcam/2.jpg','images/products/clearcam-1080p-webcam/3.jpg'],
 false),

('padx-wireless-controller',
 'Wireless Game Controller', 'PadX',
 (select id from public.categories where slug='peripherals'),
 65000, 72000, 22, 4.4, 276, null,
 'Responsive wireless controller for PC, Android and iOS with 30-hour battery.',
 $d$Play your favourite games the way they were meant to be played. The PadX controller has a familiar layout, textured grips and responsive hall-effect triggers that stay accurate for years without drifting. Connect by Bluetooth to a PC, phone or tablet, or use the USB cable for a wired, low-latency connection. With a battery that lasts around 30 hours, you can play for days before needing a charge. Two rear paddles can be mapped to any button, and built-in vibration adds to the feel of every game. A phone clip is supported, so mobile gaming is comfortable too.$d$,
 array['Hall-effect analogue triggers that resist drift',
       'Bluetooth and wired USB-C connection',
       'Up to 30 hours of battery life',
       'Two remappable rear paddles',
       'Dual vibration motors',
       'Works with PC, Android and iOS'],
 '{"Type":"Wireless gamepad","Connectivity":"Bluetooth 5.0, USB-C","Battery":"1,000mAh","Battery Life":"Up to 30 hours","Vibration":"Dual motor","Compatibility":"Windows, Android, iOS","Weight":"240 g","Colour":"Black and Red"}'::jsonb,
 array['Controller','USB-C cable','Phone clip','User guide'],
 '12 months seller warranty',
 array['images/products/padx-wireless-controller/1.jpg','images/products/padx-wireless-controller/2.jpg','images/products/padx-wireless-controller/3.jpg'],
 false),

-- =========================== DISPLAYS ===========================
('vistaview-34-ultrawide-monitor',
 '34-inch Curved Ultrawide Monitor 144Hz', 'Vistaview',
 (select id from public.categories where slug='displays'),
 980000, 1150000, 6, 4.7, 73, 'Deal',
 '34-inch curved WQHD ultrawide with 144Hz refresh rate for work and gaming.',
 $d$Replace two screens with one. The Vistaview 34-inch ultrawide gives you a wide, immersive canvas for spreadsheets, editing timelines, coding and gaming. The gentle 1500R curve wraps around your field of view, reducing eye movement and making long sessions more comfortable. A 144Hz refresh rate and 1ms response time keep fast action smooth and clear, while the WQHD 3440 x 1440 resolution shows plenty of detail. The VA panel delivers deep contrast and covers 99 percent of sRGB. Flicker-free technology and a low blue light mode help reduce eye strain, and the height-adjustable stand lets you find the right viewing position.$d$,
 array['34-inch curved ultrawide, 3440 x 1440 resolution',
       '144Hz refresh rate and 1ms response time',
       '99 percent sRGB for accurate colour',
       'Flicker-free with low blue light mode',
       'Height, tilt and swivel adjustable stand',
       'HDMI, DisplayPort and USB-C inputs'],
 '{"Screen Size":"34 inch","Resolution":"3440 x 1440 (WQHD)","Panel":"VA, 1500R curve","Refresh Rate":"144Hz","Response Time":"1ms (MPRT)","Colour Coverage":"99 percent sRGB","Ports":"2 x HDMI, 1 x DisplayPort, 1 x USB-C","Weight":"7.8 kg with stand"}'::jsonb,
 array['Monitor','Stand and base','DisplayPort cable','HDMI cable','Power cable','Quick start guide'],
 '24 months seller warranty',
 array['images/products/vistaview-34-ultrawide-monitor/1.jpg','images/products/vistaview-34-ultrawide-monitor/2.jpg','images/products/vistaview-34-ultrawide-monitor/3.jpg'],
 true),

('vistaview-27-4k-monitor',
 '27-inch 4K IPS Monitor', 'Vistaview',
 (select id from public.categories where slug='displays'),
 720000, null, 9, 4.6, 118, null,
 'Sharp 27-inch 4K IPS display with accurate colour and USB-C charging.',
 $d$See every detail. The Vistaview 27-inch 4K monitor packs 8 million pixels into an IPS panel with wide viewing angles, so text is razor sharp and photos look true from any seat. It covers 99 percent of sRGB and ships factory-calibrated, making it a great choice for photo editing, design and everyday office work. A single USB-C cable carries video, data and up to 65W of power to your laptop, cutting the clutter on your desk. Built-in speakers, a height-adjustable stand and a pivot mode for vertical reading make it flexible, while flicker-free backlighting keeps your eyes comfortable.$d$,
 array['27-inch 4K (3840 x 2160) IPS panel',
       '99 percent sRGB, factory calibrated',
       'USB-C with 65W power delivery',
       '178-degree wide viewing angles',
       'Height, tilt, swivel and pivot stand',
       'Flicker-free with low blue light mode'],
 '{"Screen Size":"27 inch","Resolution":"3840 x 2160 (4K UHD)","Panel":"IPS","Refresh Rate":"60Hz","Brightness":"350 nits","Colour Coverage":"99 percent sRGB","Ports":"2 x HDMI, 1 x DisplayPort, 1 x USB-C (65W)","Weight":"6.1 kg with stand"}'::jsonb,
 array['Monitor','Stand and base','USB-C cable','HDMI cable','Power cable','Quick start guide'],
 '24 months seller warranty',
 array['images/products/vistaview-27-4k-monitor/1.jpg','images/products/vistaview-27-4k-monitor/2.jpg','images/products/vistaview-27-4k-monitor/3.jpg'],
 true),

('lumio-24-fhd-monitor',
 '24-inch Full HD Monitor 75Hz', 'Lumio',
 (select id from public.categories where slug='displays'),
 215000, 240000, 30, 4.4, 356, 'Popular',
 'Affordable 24-inch Full HD IPS monitor with slim bezels and eye-care mode.',
 $d$A dependable everyday monitor for home, school and office. The Lumio 24-inch display uses an IPS panel that keeps colours consistent from any angle, and the Full HD resolution gives you crisp text and clear video. Slim bezels on three sides make it ideal for a two-monitor setup. A 75Hz refresh rate feels smoother than standard screens when scrolling and moving windows. Flicker-free backlighting and a low blue light mode reduce eye fatigue during long days. It includes both HDMI and VGA inputs, so it connects easily to new and older computers, and it can be mounted on the wall using the standard VESA pattern.$d$,
 array['24-inch Full HD (1920 x 1080) IPS panel',
       '75Hz refresh rate for smoother scrolling',
       'Slim bezels, great for dual-screen setups',
       'Flicker-free with low blue light mode',
       'HDMI and VGA inputs',
       'VESA 100 x 100 wall-mount compatible'],
 '{"Screen Size":"24 inch","Resolution":"1920 x 1080 (Full HD)","Panel":"IPS","Refresh Rate":"75Hz","Brightness":"250 nits","Viewing Angle":"178 degrees","Ports":"1 x HDMI, 1 x VGA","Weight":"3.2 kg with stand"}'::jsonb,
 array['Monitor','Stand and base','HDMI cable','Power adapter','Quick start guide'],
 '12 months seller warranty',
 array['images/products/lumio-24-fhd-monitor/1.jpg','images/products/lumio-24-fhd-monitor/2.jpg','images/products/lumio-24-fhd-monitor/3.jpg'],
 false),

('lumio-portable-monitor',
 '15.6-inch Portable USB-C Monitor', 'Lumio',
 (select id from public.categories where slug='displays'),
 245000, null, 12, 4.3, 64, 'New',
 'Slim 15.6-inch Full HD portable screen powered by a single USB-C cable.',
 $d$Add a second screen to your laptop wherever you work. The Lumio portable monitor is only 9mm thin and weighs under 800 grams, so it slips into your laptop bag with ease. Connect it with one USB-C cable that carries both power and video, with no extra adapter needed on most modern laptops and phones. The 15.6-inch Full HD IPS display is bright and sharp, and the included folding cover doubles as a stand in landscape or portrait. Use it to extend or mirror your laptop, plug in a phone for desktop mode, or hook up a games console with the mini HDMI port.$d$,
 array['Slim 9mm body, under 800 g',
       'Single USB-C cable for power and video',
       '15.6-inch Full HD IPS display',
       'Folding cover works as a stand',
       'Mini HDMI for consoles and cameras',
       'Built-in speakers'],
 '{"Screen Size":"15.6 inch","Resolution":"1920 x 1080 (Full HD)","Panel":"IPS","Brightness":"300 nits","Ports":"2 x USB-C, 1 x mini HDMI","Power":"Via USB-C (5V/9V)","Thickness":"9 mm","Weight":"780 g"}'::jsonb,
 array['Portable monitor','Folding cover stand','USB-C to USB-C cable','USB-A to USB-C cable','Mini HDMI to HDMI cable','Quick start guide'],
 '12 months seller warranty',
 array['images/products/lumio-portable-monitor/1.jpg','images/products/lumio-portable-monitor/2.jpg','images/products/lumio-portable-monitor/3.jpg'],
 false),

-- ========================== ACCESSORIES ==========================
('aura-felt-desk-pad',
 'Felt Desk Pad (90 x 40 cm)', 'Aura',
 (select id from public.categories where slug='accessories'),
 28000, null, 75, 4.5, 210, null,
 'Large soft felt desk mat with non-slip base that fits keyboard and mouse.',
 $d$Give your desk a clean, cosy look and protect its surface at the same time. The Aura desk pad is large enough for your keyboard, mouse and notebook, at 90 x 40 cm. The top is made from soft wool-blend felt that feels warm under your wrists and gives your mouse a smooth glide. A non-slip rubber base keeps the pad in place, and the stitched edges will not fray. It protects your desk from scratches, spills and heat, and it reduces the clatter of typing. Wipe it with a damp cloth to clean. Available in a calm grey that suits any setup.$d$,
 array['Large 90 x 40 cm surface',
       'Soft felt top, smooth mouse glide',
       'Non-slip rubber base',
       'Stitched edges that will not fray',
       'Protects desk from scratches and spills',
       'Easy to wipe clean'],
 '{"Dimensions":"90 x 40 cm","Thickness":"4 mm","Top Material":"Wool-blend felt","Base Material":"Natural rubber","Edge":"Stitched","Colour":"Slate Grey","Weight":"650 g"}'::jsonb,
 array['1 x desk pad'],
 '6 months seller warranty',
 array['images/products/aura-felt-desk-pad/1.jpg','images/products/aura-felt-desk-pad/2.jpg','images/products/aura-felt-desk-pad/3.jpg'],
 false),

('aura-laptop-stand',
 'Aluminium Laptop Stand', 'Aura',
 (select id from public.categories where slug='accessories'),
 36500, 42000, 48, 4.6, 327, 'Best seller',
 'Foldable aluminium stand with six height levels for laptops up to 17 inches.',
 $d$Raise your screen to eye level and feel the difference in your neck and shoulders. The Aura laptop stand is made from solid aluminium that holds laptops up to 17 inches and 10kg without wobbling. Six height levels let you find the right angle for typing or video calls, and the open design lets air flow under your laptop to keep it cooler. Silicone pads protect your laptop and stop it sliding. When you are done, it folds flat to just 1.2cm thick and fits in a laptop bag, so you can take it to the office, a cafe or a co-working space.$d$,
 array['Solid aluminium, holds up to 10 kg',
       'Six adjustable height levels',
       'Folds flat for easy carrying',
       'Open design improves airflow',
       'Silicone pads protect your laptop',
       'Fits laptops from 10 to 17 inches'],
 '{"Material":"Aluminium alloy","Compatible Sizes":"10 to 17 inch laptops","Max Load":"10 kg","Height Levels":"6 (6 cm to 15 cm)","Folded Thickness":"1.2 cm","Weight":"280 g","Colour":"Silver"}'::jsonb,
 array['Laptop stand','Carry pouch','Spare silicone pads'],
 '12 months seller warranty',
 array['images/products/aura-laptop-stand/1.jpg','images/products/aura-laptop-stand/2.jpg','images/products/aura-laptop-stand/3.jpg'],
 false),

('linkport-7in1-usb-c-hub',
 '7-in-1 USB-C Docking Hub', 'Linkport',
 (select id from public.categories where slug='accessories'),
 52000, null, 42, 4.4, 198, null,
 'USB-C hub with 4K HDMI, USB 3.0, SD card reader and 100W pass-through charging.',
 $d$Turn one USB-C port into seven. The Linkport hub adds a 4K HDMI output, two USB 3.0 ports, an SD card slot, a microSD slot, an Ethernet port and USB-C power pass-through to your slim laptop. Connect a monitor, transfer photos from your camera, plug in a wired network and charge your laptop with up to 100W, all at once. The aluminium shell dissipates heat and matches most laptops, and the short built-in cable keeps things tidy. It works with MacBooks, Windows laptops, iPads with USB-C and many Android phones.$d$,
 array['4K HDMI output at 30Hz',
       '2 x USB 3.0 ports (5Gbps)',
       'SD and microSD card readers',
       'Gigabit Ethernet port',
       '100W USB-C pass-through charging',
       'Compact aluminium body'],
 '{"Ports":"1 x HDMI, 2 x USB-A 3.0, 1 x SD, 1 x microSD, 1 x RJ45, 1 x USB-C PD","Video Output":"4K at 30Hz","Data Speed":"Up to 5Gbps","Power Pass-through":"Up to 100W","Cable Length":"15 cm","Material":"Aluminium","Weight":"85 g"}'::jsonb,
 array['USB-C hub','Protective pouch','User guide'],
 '12 months seller warranty',
 array['images/products/linkport-7in1-usb-c-hub/1.jpg','images/products/linkport-7in1-usb-c-hub/2.jpg','images/products/linkport-7in1-usb-c-hub/3.jpg'],
 false),

('aura-laptop-sleeve',
 '14-inch Padded Laptop Sleeve', 'Aura',
 (select id from public.categories where slug='accessories'),
 22000, null, 90, 4.2, 152, null,
 'Water-resistant padded sleeve with soft lining and accessory pocket.',
 $d$Keep your laptop safe from bumps, scratches and surprise rain. The Aura sleeve fits laptops up to 14 inches and uses thick foam padding that absorbs knocks if your bag is dropped. The water-resistant outer fabric shrugs off splashes, and the soft microfibre lining protects the screen and body from scratches. A smooth zip opens wide for easy access, and a front pocket holds your charger, mouse or a few cables. It is slim enough to slide into a backpack or carry on its own.$d$,
 array['Fits laptops up to 14 inches',
       'Thick shock-absorbing foam padding',
       'Water-resistant outer fabric',
       'Soft microfibre lining',
       'Front pocket for charger and accessories',
       'Smooth wide-opening zip'],
 '{"Fits":"Up to 14 inch laptops","Outer Material":"Water-resistant polyester","Lining":"Microfibre","Padding":"8 mm foam","Internal Size":"33 x 24 x 2 cm","Closure":"Zip","Colour":"Charcoal","Weight":"290 g"}'::jsonb,
 array['1 x laptop sleeve'],
 '6 months seller warranty',
 array['images/products/aura-laptop-sleeve/1.jpg','images/products/aura-laptop-sleeve/2.jpg','images/products/aura-laptop-sleeve/3.jpg'],
 false),

-- ====================== POWER AND CHARGING ======================
('voltix-65w-gan-charger',
 '65W GaN USB-C Fast Charger', 'Voltix',
 (select id from public.categories where slug='power-and-charging'),
 42000, 48000, 55, 4.6, 433, 'Popular',
 'Compact 65W GaN charger that fast-charges a laptop and phone at the same time.',
 $d$One small charger for all your devices. Thanks to GaN technology, the Voltix 65W charger is about half the size of a traditional laptop charger while staying cool to the touch. Its two USB-C ports and one USB-A port charge a laptop, phone and earbuds together, sharing power intelligently. A single USB-C port delivers up to 65W, enough for most ultrabooks, tablets and the latest phones. Built-in protection guards against overheating, over-voltage and short circuits. The folding plug makes it easy to pack. Replace your bulky chargers and travel lighter.$d$,
 array['65W output charges most laptops',
       'Compact GaN design, half the size of standard chargers',
       '2 x USB-C and 1 x USB-A ports',
       'Charges three devices at once',
       'Built-in overheat and surge protection',
       'Foldable plug for travel'],
 '{"Output Power":"65W maximum","Ports":"2 x USB-C, 1 x USB-A","Protocols":"USB PD 3.0, PPS, QC 4+","Input":"100 to 240V","Protection":"Over-voltage, over-current, overheat","Plug Type":"Type G (UK), foldable","Weight":"118 g","Colour":"White"}'::jsonb,
 array['65W GaN charger','1 m USB-C to USB-C cable','User guide'],
 '12 months seller warranty',
 array['images/products/voltix-65w-gan-charger/1.jpg','images/products/voltix-65w-gan-charger/2.jpg','images/products/voltix-65w-gan-charger/3.jpg'],
 false),

('voltix-20000mah-power-bank',
 '20,000mAh Power Bank', 'Voltix',
 (select id from public.categories where slug='power-and-charging'),
 54000, null, 70, 4.5, 612, 'Best seller',
 '20,000mAh power bank with 22.5W fast charging and a digital battery display.',
 $d$Never run out of power again, especially when light is unreliable. The Voltix power bank stores 20,000mAh, enough to charge most phones four to five times or a tablet more than once. Fast 22.5W output tops up a modern phone to 50 percent in about 30 minutes, and two outputs let you charge two devices at the same time. A digital display shows the exact battery percentage, so you always know how much is left. Pass-through charging lets you charge the power bank and your phone together, and multi-layer protection keeps your devices safe. Airline-friendly and built tough for daily carrying.$d$,
 array['20,000mAh capacity, about 4 to 5 phone charges',
       '22.5W fast charging',
       'Digital battery percentage display',
       'Charges two devices at once',
       'USB-C input and output',
       'Multi-layer safety protection'],
 '{"Capacity":"20,000mAh (74Wh)","Output":"22.5W maximum","Ports":"1 x USB-C (in/out), 2 x USB-A","Input":"18W via USB-C","Display":"Digital percentage","Dimensions":"15.0 x 7.2 x 2.7 cm","Weight":"430 g","Colour":"Black"}'::jsonb,
 array['Power bank','USB-C charging cable','Carry pouch','User guide'],
 '12 months seller warranty',
 array['images/products/voltix-20000mah-power-bank/1.jpg','images/products/voltix-20000mah-power-bank/2.jpg','images/products/voltix-20000mah-power-bank/3.jpg'],
 true),

('voltix-surge-protector',
 '6-Socket Surge Protector Extension', 'Voltix',
 (select id from public.categories where slug='power-and-charging'),
 24500, null, 80, 4.3, 284, null,
 'Six-socket extension with surge protection, 2 USB ports and a 3-metre cable.',
 $d$Protect your computer, monitor and chargers from power surges. The Voltix extension has six sockets with a built-in surge protection circuit that absorbs spikes before they reach your equipment, plus two USB ports for charging phones without extra adapters. A master switch with indicator light lets you cut power to everything at once, and a safety shutter closes off unused sockets. The 3-metre heavy-duty cable reaches across the room, and the flame-retardant casing adds an extra layer of safety. Mount it on a wall or place it under your desk.$d$,
 array['Surge protection for sensitive electronics',
       '6 sockets plus 2 USB charging ports',
       'Master switch with indicator light',
       'Child-safe shutters on sockets',
       '3-metre heavy-duty cable',
       'Flame-retardant casing'],
 '{"Sockets":"6 x UK-style","USB Ports":"2 x USB-A (2.4A total)","Cable Length":"3 m","Rated Load":"13A / 3,250W","Protection":"Surge, overload, flame retardant","Switch":"Master switch with indicator","Weight":"540 g","Colour":"White"}'::jsonb,
 array['Extension socket','User guide'],
 '12 months seller warranty',
 array['images/products/voltix-surge-protector/1.jpg','images/products/voltix-surge-protector/2.jpg','images/products/voltix-surge-protector/3.jpg'],
 false),

('voltix-wireless-charging-pad',
 '15W Wireless Charging Pad', 'Voltix',
 (select id from public.categories where slug='power-and-charging'),
 19500, 22500, 100, 4.1, 145, 'Deal',
 'Slim 15W wireless charging pad for phones and earbuds, works through most cases.',
 $d$Drop your phone on the pad and it starts charging, with no cables to plug and unplug. The Voltix pad supports up to 15W fast wireless charging for compatible phones and 5W for earbuds with wireless cases. It charges through most cases up to 5mm thick, so you do not need to remove yours. A soft LED shows charging status, and a non-slip surface holds the phone steady. Built-in safety features detect metal objects, overheating and over-current. Perfect for a bedside table or office desk.$d$,
 array['Up to 15W fast wireless charging',
       'Works through cases up to 5 mm thick',
       'Non-slip surface keeps phone in place',
       'Soft LED charging indicator',
       'Foreign-object and overheat protection',
       'Also charges wireless earbuds'],
 '{"Output":"15W maximum (phones), 5W (earbuds)","Standard":"Qi","Input":"USB-C, 9V/2A","Case Support":"Up to 5 mm","Indicator":"LED","Dimensions":"10 cm diameter, 8 mm thick","Weight":"85 g","Colour":"Black"}'::jsonb,
 array['Wireless charging pad','USB-C cable (1 m)','User guide'],
 '6 months seller warranty',
 array['images/products/voltix-wireless-charging-pad/1.jpg','images/products/voltix-wireless-charging-pad/2.jpg','images/products/voltix-wireless-charging-pad/3.jpg'],
 false),

-- ============================ WORKSPACE ============================
('lumio-led-desk-lamp',
 'Adjustable LED Desk Lamp with Dimmer', 'Lumio',
 (select id from public.categories where slug='workspace'),
 38000, null, 45, 4.5, 238, null,
 'Eye-care LED lamp with 5 colour modes, 5 brightness levels and wireless charging base.',
 $d$Good light makes long hours of study and work easier. The Lumio desk lamp gives you five colour temperatures from warm to cool and five brightness levels, so you can choose the right light for reading, working or winding down. The flicker-free LED and wide, even beam reduce eye strain, and the flexible arm and pivoting head put light exactly where you need it. The base doubles as a 10W wireless charger for your phone. Touch controls are easy to use in the dark, and the memory function returns to your last setting when you switch it on.$d$,
 array['5 colour temperatures and 5 brightness levels',
       'Flicker-free eye-care LED',
       'Built-in 10W wireless charging base',
       'Flexible arm and rotating head',
       'Touch controls with memory function',
       'Auto-off timer'],
 '{"Light Source":"LED","Colour Temperature":"3000K to 6500K","Brightness Levels":"5","Power":"12W lamp, 10W wireless charging","Input":"USB-C, 12V adapter","Arm":"Flexible with pivot head","Weight":"850 g","Colour":"White"}'::jsonb,
 array['Desk lamp','Power adapter','User guide'],
 '12 months seller warranty',
 array['images/products/lumio-led-desk-lamp/1.jpg','images/products/lumio-led-desk-lamp/2.jpg','images/products/lumio-led-desk-lamp/3.jpg'],
 false),

('sitwell-mesh-office-chair',
 'Ergonomic Mesh Office Chair', 'Sitwell',
 (select id from public.categories where slug='workspace'),
 310000, 360000, 8, 4.6, 131, 'Best seller',
 'Breathable mesh chair with lumbar support, adjustable armrests and 135-degree recline.',
 $d$Sit comfortably through the longest days. The Sitwell chair has a breathable mesh back that keeps you cool in warm weather, and an adjustable lumbar support that follows the curve of your spine. The seat height, armrests and headrest all adjust, so the chair fits you whatever your size. Recline up to 135 degrees and lock the position when you want to lean back and think. A thick moulded-foam seat stays supportive over time, and the smooth-rolling casters work on hard floors and tiles. The strong nylon base supports up to 150kg.$d$,
 array['Breathable mesh back keeps you cool',
       'Adjustable lumbar support and headrest',
       '3D adjustable armrests',
       '135-degree recline with lock',
       'Supports up to 150 kg',
       'Smooth-rolling silent casters'],
 '{"Back Material":"Breathable mesh","Seat":"High-density moulded foam","Max Load":"150 kg","Seat Height":"45 to 55 cm","Recline":"Up to 135 degrees","Armrests":"3D adjustable","Base":"Reinforced nylon, 5 casters","Weight":"17 kg","Colour":"Black"}'::jsonb,
 array['Chair parts','Gas lift','Tools for assembly','Assembly guide'],
 '24 months seller warranty',
 array['images/products/sitwell-mesh-office-chair/1.jpg','images/products/sitwell-mesh-office-chair/2.jpg','images/products/sitwell-mesh-office-chair/3.jpg'],
 true),

('sitwell-standing-desk',
 'Electric Height-Adjustable Standing Desk', 'Sitwell',
 (select id from public.categories where slug='workspace'),
 465000, null, 0, 4.7, 88, null,
 'Electric sit-stand desk with memory presets and a 120 x 60 cm tabletop.',
 $d$Switch between sitting and standing at the touch of a button. The Sitwell desk uses a dual-motor frame that lifts smoothly and quietly from 72cm to 120cm, carrying up to 80kg. The control panel stores four height presets, so your perfect sitting and standing positions are one tap away. A collision sensor stops the desk if it meets an obstacle, and the sturdy steel frame stays stable at full height. The 120 x 60cm tabletop fits a monitor, laptop and accessories. A cable tray keeps wires tidy. Alternating between sitting and standing can make long work days more comfortable.$d$,
 array['Quiet dual-motor electric lift',
       'Height range 72 to 120 cm',
       '4 memory presets',
       'Anti-collision protection',
       'Supports up to 80 kg',
       'Includes cable tray'],
 '{"Tabletop":"120 x 60 cm","Height Range":"72 to 120 cm","Motor":"Dual motor","Lift Speed":"38 mm per second","Max Load":"80 kg","Presets":"4 memory positions","Frame":"Powder-coated steel","Weight":"38 kg"}'::jsonb,
 array['Tabletop','Steel frame and legs','Control panel','Cable tray','Tools and screws','Assembly guide'],
 '24 months seller warranty',
 array['images/products/sitwell-standing-desk/1.jpg','images/products/sitwell-standing-desk/2.jpg','images/products/sitwell-standing-desk/3.jpg'],
 false),

('lumio-monitor-light-bar',
 'Monitor Light Bar', 'Lumio',
 (select id from public.categories where slug='workspace'),
 34000, null, 36, 4.4, 173, null,
 'Clip-on monitor light bar with asymmetric beam, no screen glare and auto-dimming.',
 $d$Light your desk without lighting your screen. The Lumio light bar sits on top of your monitor and uses an asymmetric beam that shines down onto your keyboard and papers while keeping glare off the display. It frees up desk space, since there is no lamp base. The auto-dimming sensor adjusts brightness to the room, or you can set the colour temperature and brightness by hand with the wireless dial. A clip fits most monitors between 1 and 3cm thick, including curved screens, and the USB power cable plugs into your monitor or computer.$d$,
 array['Asymmetric light reduces screen glare',
       'Auto-dimming ambient light sensor',
       'Adjustable colour temperature 2700K to 6500K',
       'Wireless control dial',
       'Fits flat and curved monitors',
       'USB powered, saves desk space'],
 '{"Light Source":"LED","Colour Temperature":"2700K to 6500K","Brightness":"Up to 500 lux","Control":"Wireless dial and touch","Power":"USB-A, 5V","Monitor Thickness":"1 to 3 cm","Length":"45 cm","Weight":"330 g"}'::jsonb,
 array['Light bar','Wireless control dial','USB cable (1.5 m)','User guide'],
 '12 months seller warranty',
 array['images/products/lumio-monitor-light-bar/1.jpg','images/products/lumio-monitor-light-bar/2.jpg','images/products/lumio-monitor-light-bar/3.jpg'],
 false)

on conflict (slug) do update set
  name              = excluded.name,
  brand             = excluded.brand,
  category_id       = excluded.category_id,
  price             = excluded.price,
  old_price         = excluded.old_price,
  badge             = excluded.badge,
  short_description = excluded.short_description,
  description       = excluded.description,
  highlights        = excluded.highlights,
  specifications    = excluded.specifications,
  box_contents      = excluded.box_contents,
  warranty          = excluded.warranty,
  image_urls        = excluded.image_urls,
  is_featured       = excluded.is_featured;

-- ---------------------------------------------------------------------
-- 3. CHECK (you should see 6 categories and 24 products, 8 featured,
--    1 sold out, and 11 with an old price)
-- ---------------------------------------------------------------------
select
  (select count(*) from public.categories)                     as categories,
  (select count(*) from public.products)                       as products,
  (select count(*) from public.products where is_featured)     as featured,
  (select count(*) from public.products where stock_qty = 0)   as sold_out,
  (select count(*) from public.products where old_price is not null) as with_old_price;
